services:
  backend:
    build: ./backend
    ports:
      - "3000:3000"
    volumes:
      - type: volume
        source: db-data
        target: /backend/db-data
    networks:
      - back-tier
    develop:
      watch:
        - action: rebuild
          path: ./backend
          target: Hivemind/backend
          ignore:
            - node_modules/
        - action: rebuild
          path: package.json
  frontend:
    build: ./frontend/angular-app
    ports:
      - "4200:4200"
    networks:
      - front-tier
      - back-tier
    depends_on:
      backend:
        condition: service_started
        restart: true
    develop:
      watch:
        - action: rebuild
          path: ./frontend/angular-app
          target: Hivemind/frontend/angular-app
          ignore:
            - node_modules/
        - action: rebuild
          path: package.json

volumes:
  db-data:

configs:
  httpd-config:
    external: true

networks:
  front-tier: {}
  back-tier: {}
