ARG NODE_VERSION=18-slim
FROM node:slim

ENV NODE_ENV production
WORKDIR /backend

RUN --mount=type=bind,source=package.json,target=package.json \
    --mount=type=bind,source=package-lock.json,target=package-lock.json \
    --mount=type=cache,target=/root/.npm \
    npm ci --omit=dev

USER node

COPY . .

EXPOSE 3000

CMD node index.js